[package]
name = "bzauth-rs"
version = "0.1.0"
edition = "2024"

[features]
default = ["axum", "diesel", "sqlite", "test_unsafe_logging"]

# Adapter features
diesel = ["dep:diesel"] # diesel -> adapt_diesel
sqlx = ["dep:sqlx"]     # sqlx -> adapt_sqlx

# Runtime features
axum = ["dep:axum"]       # Pulls in axum runtime support
actix = ["dep:actix-web"] # Pulls in actix-web runtime support

# Backend features
sqlite = [
  "diesel?/sqlite",
  "diesel?/returning_clauses_for_sqlite_3_35",
  "sqlx?/sqlite",
] # SQLite support
postgres = [] # TODO: Add Postgres support

# Testing features
test_sequential = []
test_unsafe_logging = []

[dependencies]
# Core dependencies
tokio = { version = "1.46", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
oauth2 = "5.0"
reqwest = { version = "0.12", features = ["json", "cookies"] }

# Supported runtimes
axum = { version = "0.8", features = ["macros", "json"], optional = true }
actix-web = { version = "4.11", features = ["macros"], optional = true }   # TODO

# Data adapters
diesel = { version = "2.2", features = ["r2d2", "chrono"], optional = true }
sqlx = { version = "0.8", features = [
  "runtime-tokio-rustls",
  "chrono",
], optional = true }

# Utilities
async-trait = "0.1"
dyn-clone = "1.0"
paste = "1.0"

chrono = "0.4"
cookie = "0.18"
http = "1.3"
url = "2.5"
rand = "0.9"
uuid = { version = "1.17", features = ["v4"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3.20"
once_cell = "1.21"

#
# Tests
#

[[test]]
name = "test_03_environment"
required-features = ["test_sequential"]
